version: '2'
services:
 mysql:  
  image: mysql
  container_name: mysql
  ports:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=flaskblog
   - MYSQL_USER=flaskblog
   - MYSQL_PASSWORD=flaskblog
 flask_blog:  
  build: flask_blog 
  container_name: flask_blog
  depends_on:
    - mysql
  links:
    - mysql
  ports:
    - "5000:5000"

